### ISSUE TITLE
H1 repetido

### ISSUE THREAD

**Issue by juanhuttemann** [HuttSoft/testGit#3]
h1 repetido 3 veces
https://github.com/HuttSoft/testGit/blob/01afe2d1ce51698fed9ada3e5bc836ea103d98ee/index.html#L10

**Comment by tonyjara** [comment]
pesado

**Comment by tonyjara** [comment]
01afe2d1ce51698fed9ada3e5bc836ea103d98ee ahi te arregleu tu karacha
