### ISSUE TITLE
que lo que es loco?

### ISSUE THREAD

**Issue by tonyjara** [HuttSoft/testGit#4]
https://github.com/HuttSoft/testGit/blob/36002c3bb1401f2a779b204288f11972b17086a5/index.html#L14 explicame un poco esto

**Comment by juanhuttemann** [comment]
Es un titulo muy cool :100:

**Comment by tonyjara** [comment]
ahi mi subordinado acepto, cambia como estaba antes

**Comment by tonyjara** [comment]
https://github.com/HuttSoft/testGit/issues/4#issuecomment-705292013 hace 10 minutos que no hay cambios, ya puse tu laburo a disposicion
